import { create } from "zustand";
import type { EditorSnapshot, Entity, Scene } from "./types";
import { api } from "./api";
type State = { projects: string[]; project: string | null; snapshot: EditorSnapshot | null; scene: Scene | null; selectedEntity: string | null; activeScene: string | null; view: "scene" | "game"; gameUrl: string | null; bottomPanel: "console" | "assets"; logs: string[]; loading: boolean; openProject: (name: string) => Promise<void>; openScene: (file: string) => Promise<void>; selectEntity: (id: string | null) => void; updateEntity: (fn: (entity: Entity) => Entity) => void; addEntity: () => void; duplicateEntity: () => void; removeEntity: () => void; moveEntity: (id: string, x: number, y: number) => void; save: () => Promise<void>; build: () => Promise<void>; };
export const useEditor = create<State>((set, get) => ({ projects: [], project: null, snapshot: null, scene: null, selectedEntity: null, activeScene: null, view: "scene", gameUrl: null, bottomPanel: "console", logs: ["Editor ready", "Waiting for project selection"], loading: false,
  openProject: async (name) => { set({ loading: true, project: name, logs: [`Loading ${name}...`] }); try { const snapshot = await api.editor(name); const first = snapshot.scenes[0]; set({ snapshot, loading: false, logs: [`Loaded ${name}`, `${Object.keys(snapshot.components).length} component definitions discovered`] }); if (first) await get().openScene(first); } catch (error) { set({ loading: false, logs: [...get().logs, `Error: ${error instanceof Error ? error.message : "Could not load project"}`] }); } },
  openScene: async (file) => { const project = get().project; if (!project) return; try { const scene = await api.scene(project, file.replace(/\.json$/, "")); set({ scene: scene.scene, activeScene: file, selectedEntity: scene.scene.entities[0]?.id ?? null, logs: [...get().logs, `Opened scene ${file}`] }); } catch (error) { set({ logs: [...get().logs, `Error: ${error instanceof Error ? error.message : "Could not open scene"}`] }); } },
  selectEntity: (id) => set({ selectedEntity: id }),
  updateEntity: (fn) => { const { scene, selectedEntity } = get(); if (!scene || !selectedEntity) return; set({ scene: { ...scene, entities: scene.entities.map((e) => e.id === selectedEntity ? fn(e) : e) } }); },
  addEntity: () => { const { scene } = get(); if (!scene) return; const id = `Entity_${scene.entities.length + 1}`; const entity: Entity = { id, components: { Transform: { x: 120, y: 120, rotation: 0 } }, scripts: [] }; set({ scene: { ...scene, entities: [...scene.entities, entity] }, selectedEntity: id, logs: [...get().logs, `Created entity ${id}`] }); },
  duplicateEntity: () => { const { scene, selectedEntity } = get(); if (!scene || !selectedEntity) return; const source = scene.entities.find(e => e.id === selectedEntity); if (!source) return; const id = `${source.id}_copy`; let unique = id; let count = 2; while (scene.entities.some(e => e.id === unique)) unique = `${id}_${count++}`; const copy: Entity = JSON.parse(JSON.stringify({ ...source, id: unique })); const transform = copy.components?.Transform; if (transform) { transform.x = Number(transform.x ?? 0) + 24; transform.y = Number(transform.y ?? 0) + 24; } set({ scene: { ...scene, entities: [...scene.entities, copy] }, selectedEntity: unique, logs: [...get().logs, `Duplicated ${selectedEntity} as ${unique}`] }); },
  removeEntity: () => { const { scene, selectedEntity } = get(); if (!scene || !selectedEntity) return; set({ scene: { ...scene, entities: scene.entities.filter(e => e.id !== selectedEntity) }, selectedEntity: scene.entities.find(e => e.id !== selectedEntity)?.id ?? null, logs: [...get().logs, `Removed entity ${selectedEntity}`] }); },
  moveEntity: (id, x, y) => { const { scene } = get(); if (!scene) return; set({ scene: { ...scene, entities: scene.entities.map(e => e.id === id ? { ...e, components: { ...e.components, Transform: { ...(e.components?.Transform ?? {}), x, y } } } : e) } }); },
  save: async () => { const { project, activeScene, scene } = get(); if (!project || !activeScene || !scene) return; try { await api.saveScene(project, activeScene.replace(/\.json$/, ""), scene); set({ logs: [...get().logs, `Saved ${activeScene}`] }); } catch (error) { set({ logs: [...get().logs, `Save error: ${error instanceof Error ? error.message : "Could not save scene"}`] }); } },
  build: async () => { const project = get().project; if (!project) return; try { await get().save(); const result = await api.build(project); set({ view: "game", gameUrl: result.url, logs: [...get().logs, `Build complete: ${result.url}`] }); } catch (error) { set({ logs: [...get().logs, `Build error: ${error instanceof Error ? error.message : "Could not build project"}`] }); } }
}));
